# Generated by Django 3.1.7 on 2021-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('product_desc', models.CharField(default='', max_length=500)),
                ('product_img', models.ImageField(upload_to='static/images')),
                ('product_type', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='udetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
