# Generated by Django 3.1.7 on 2021-04-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udetails',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='udetails',
            name='phnnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='udetails',
            name='uname',
            field=models.CharField(default='ck', max_length=100),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_sno', models.AutoField(db_column='order_sno', primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=200)),
                ('order_price', models.IntegerField()),
                ('order_img', models.CharField(default='', max_length=200, null=True)),
                ('numofprod', models.IntegerField(default=1)),
                ('uname', models.CharField(default='', max_length=200, null=True)),
                ('order_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ckwebsite.product')),
            ],
        ),
    ]
