# Generated by Django 3.1.7 on 2021-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('uname', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=200)),
                ('order_price', models.IntegerField()),
                ('order_img', models.CharField(max_length=200)),
                ('order_total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
