# Generated by Django 3.1.7 on 2021-04-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckwebsite', '0002_auto_20210402_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_total',
            new_name='numofprod',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='uname',
        ),
        migrations.AddField(
            model_name='udetails',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='udetails',
            name='phnnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='udetails',
            name='uname',
            field=models.CharField(max_length=300),
        ),
    ]
