# Generated by Django 3.1.7 on 2021-04-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckwebsite', '0003_auto_20210428_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordershistory',
            fields=[
                ('order_sno', models.AutoField(db_column='order_sno', primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=200)),
                ('order_price', models.IntegerField()),
                ('order_img', models.CharField(default='', max_length=200, null=True)),
                ('numofprod', models.IntegerField(default=1)),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('order_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ckwebsite.product')),
            ],
        ),
    ]
